### ISSUE TITLE
[BUG] Error When Opneing Grimoire

### ISSUE THREAD

**Issue by StevenEvans1966** [Forien/foundryvtt-forien-armoury#49]
using whfrp v8.0.4 get following when pressing Edit Item for Grimoire

foundry-esm.js:4621 Error: The {{select}} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or the foundry.applications.fields.createSelectInput, foundry.applications.fields.createMultiSelectElement, or foundry.applications.fields.prepareSelectOptionGroups methods.
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Object.select (foundry.js:8349:19)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:29:129)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async GrimoireSheet._renderInner (foundry.js:6013:16)
    at async GrimoireSheet._renderInner (foundry.js:6583:18)
    at async GrimoireSheet._render (foundry.js:5844:19)
    at async GrimoireSheet._render (foundry.js:6572:5)
    at async GrimoireSheet._render (foundry.js:7158:5)
    at async GrimoireSheet._render (warhammer.js:5756:9)
    at async GrimoireSheet._render (wfrp4e.js:12312:5)

**Comment by Forien** [comment]
This is not error, it's a warning (it's yellow) and it's unrelated to the module at all. It's from the system. Also it does not cause anything, it's just a notice of future deprecation.
